// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Fontları Geist olarak varsayıyorum
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>{/* <html> ETİKETİNDEN SONRA BOŞLUK VEYA YENİ SATIR YOK */}
        {/* <head> etiketi genellikle Next.js tarafından yönetilir veya _document.tsx'te olur,
          ama eğer layout.tsx'te manuel bir <head> varsa, onunla <body> arasında da boşluk olmamalı.
          Eğer <head> yoksa, doğrudan <body> ile devam edin. */}
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            suppressHydrationWarning={true}
        >{/* <body> ETİKETİNDEN SONRA BOŞLUK VEYA YENİ SATIR YOK */}
        {children}
        </body>{/* </body> ETİKETİNDEN ÖNCE BOŞLUK VEYA YENİ SATIR YOK */}
        </html>/* </html> ETİKETİNDEN ÖNCE BOŞLUK VEYA YENİ SATIR YOK */
    );
}